import type { PlayerCardProps } from "../PlayerCard";

export const initialPlayers: PlayerCardProps[] = [
  {
    id: "1",
    username: "test",
    level: 2276,
    account_type: "MAIN",
    ca_score: 2524,
    hours: "40 - 50",
    timezone: "EST",
    notes: "test",
    has_shadow: true,
    has_tbow: true,
    has_scythe: true,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "2",
    username: "ThePrestiege",
    level: 2173,
    account_type: "MAIN",
    ca_score: 1122,
    hours: "40",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: false,
    has_scythe: false,
    has_quiver: false,
    has_infernal: false,
  },
  {
    id: "3",
    username: "Maverick1184",
    level: 1916,
    account_type: "MAIN",
    ca_score: 850,
    hours: "25",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: true,
    has_scythe: false,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "4",
    username: "test",
    level: 2277,
    account_type: "MAIN",
    ca_score: 2525,
    hours: "40 - 50",
    timezone: "EST",
    notes: "test",
    has_shadow: true,
    has_tbow: true,
    has_scythe: true,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "5",
    username: "ThePrestiege",
    level: 2173,
    account_type: "MAIN",
    ca_score: 1122,
    hours: "40",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: false,
    has_scythe: false,
    has_quiver: false,
    has_infernal: false,
  },
  {
    id: "6",
    username: "Maverick1184",
    level: 1916,
    account_type: "MAIN",
    ca_score: 850,
    hours: "25",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: true,
    has_scythe: false,
    has_quiver: true,
    has_infernal: true,
  },
];