import type { PlayerCardProps } from "../PlayerCard";

export const initialPlayers: PlayerCardProps[] = [
  {
    id: "1",
    username: "test",
    level: 2276,
    account_type: "MAIN",
    ca_score: 2524,
    hours: "40 - 50",
    timezone: "EST",
    notes: "test",
    has_shadow: true,
    has_tbow: true,
    has_scythe: true,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "2",
    username: "ThePrestiege",
    level: 2173,
    account_type: "MAIN",
    ca_score: 1122,
    hours: "40",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: false,
    has_scythe: false,
    has_quiver: false,
    has_infernal: false,
  },
  {
    id: "3",
    username: "Maverick1184",
    level: 1916,
    account_type: "MAIN",
    ca_score: 850,
    hours: "25",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: true,
    has_scythe: false,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "4",
    username: "test",
    level: 2277,
    account_type: "MAIN",
    ca_score: 2525,
    hours: "40 - 50",
    timezone: "EST",
    notes: "test",
    has_shadow: true,
    has_tbow: true,
    has_scythe: true,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "5",
    username: "ThePrestiege",
    level: 2173,
    account_type: "MAIN",
    ca_score: 1122,
    hours: "40",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: false,
    has_scythe: false,
    has_quiver: false,
    has_infernal: false,
  },
  {
    id: "6",
    username: "Maverick1184",
    level: 1916,
    account_type: "MAIN",
    ca_score: 850,
    hours: "25",
    timezone: "CST",
    notes: "A true gamer",
    has_shadow: true,
    has_tbow: true,
    has_scythe: false,
    has_quiver: true,
    has_infernal: true,
  },
];

export const sampleCaptains: PlayerCardProps[] = [
  {
    id: "101",
    username: "Captain1",
    level: 2277,
    account_type: "MAIN",
    ca_score: 3000,
    hours: "50+",
    timezone: "EST",
    notes: "Captain 1 notes",
    has_shadow: true,
    has_tbow: true,
    has_scythe: true,
    has_quiver: true,
    has_infernal: true,
  },
  {
    id: "102",
    username: "Captain2",
    level: 2100,
    account_type: "IRON",
    ca_score: 2000,
    hours: "30-40",
    timezone: "PST",
    notes: "Captain 2 notes",
    has_shadow: false,
    has_tbow: true,
    has_scythe: false,
    has_quiver: false,
    has_infernal: false,
  },
  {
    id: "103",
    username: "Captain3",
    level: 1800,
    account_type: "HCIM",
    ca_score: 1500,
    hours: "20-30",
    timezone: "CST",
    notes: "Captain 3 notes",
    has_shadow: false,
    has_tbow: false,
    has_scythe: false,
    has_quiver: true,
    has_infernal: false,
  },
];