export const skills = [
  "Attack",
  "Strength",
  "Defense",
  "Ranged",
  "Prayer",
  "Magic",
  "Runecrafting",
  "Construction",
  "Hitpoints",
  "Agility",
  "Herblore",
  "Thieving",
  "Crafting",
  "Fletching",
  "Slayer",
  "Hunter",
  "Mining",
  "Smithing",
  "Fishing",
  "Cooking",
  "Firemaking",
  "Woodcutting",
  "Farming",
];

export const bosses = [
  "abyssal_sire",
  "alchemical_hydra",
  "amoxliatl",
  "araxxor",
  "artio",
  "barrows_chests",
  "bryophyta",
  "callisto",
  "calvarion",
  "cerberus",
  "chaos_elemental",
  "chaos_fanatic",
  "commander_zilyana",
  "corporeal_beast",
  "crazy_archaeologist",
  "dagannoth_prime",
  "dagannoth_rex",
  "dagannoth_supreme",
  "deranged_archaeologist",
  "duke_sucellus",
  "general_graardor",
  "giant_mole",
  "grotesque_guardians",
  "hespori",
  "kalphite_queen",
  "king_black_dragon",
  "kraken",
  "kreearra",
  "kril_tsutsaroth",
  "nex",
  "nightmare",
  "phosanis_nightmare",
  "obor",
  "phantom_muspah",
  "royal_titans",
  "sarachnis",
  "scorpia",
  "scurrius",
  "skotizo",
  "sol_heredit",
  "spindel",
  "tempoross",
  "the_hueycoatl",
  "the_leviathan",
  "the_whisperer",
  "thermonuclear_smoke_devil",
  "tzkal_zuk",
  "tztok_jad",
  "vardorvis",
  "venenatis",
  "vetion",
  "vorkath",
  "wintertodt",
  "yama",
  "zalcano",
  "zulrah",
];

export const raids = [
  "chambers_of_xeric",
  "chambers_of_xeric_challenge_mode",
  "theatre_of_blood",
  "theatre_of_blood_hard_mode",
  "tombs_of_amascut",
  "tombs_of_amascut_expert",
];

export const memberSkills = [
  "agility",
  "construction",
  "farming",
  "fletching",
  "herblore",
  "hunter",
  "slayer",
  "thieving",
];
export const wildernessBosses = [
  "artio",
  "callisto",
  "calvarion",
  "chaos_elemental",
  "chaos_fanatic",
  "crazy_archaeologist",
  "scorpia",
  "spindel",
  "venenatis",
  "vetion",
];
export const slayerOnlyMonsters = [
  "abyssal_sire",
  "alchemical_hydra",
  "araxxor",
  "cerberus",
  "kraken",
  "thermonuclear_smoke_devil",
  "grotesque_guardians",
];
export const multiCombatBosses = [
  "corporeal_beast",
  "nex",
  "the_hueycoatl",
  "general_graardor",
  "commander_zilyana",
  "kreearra",
  "kril_tsutsaroth",
  "king_black_dragon",
  "scurrius",
  "royal_titans",
  "nightmare",
  "tempoross",
  "zalcano",
  "wintertodt",
];
export const hardModeRaids = [
  "chambers_of_xeric_challenge_mode",
  "theatre_of_blood_hard_mode",
  "tombs_of_amascut_expert",
];

export const clueScrolls = [
  "clue_scrolls_all",
  "clue_scrolls_beginner",
  "clue_scrolls_easy",
  "clue_scrolls_medium",
  "clue_scrolls_hard",
  "clue_scrolls_elite",
  "clue_scrolls_master",
  "mimic",
];

export const clueScrollColors: { [key: string]: string } = {
  clue_scrolls_all: "black",
  clue_scrolls_beginner: "#5b3e00",
  clue_scrolls_easy: "#00FF00",
  clue_scrolls_medium: "#00f3ff",
  clue_scrolls_hard: "#cc01d9",
  clue_scrolls_elite: "#ffe229",
  clue_scrolls_master: "#FF0000",
  mimic: "black",
};

import {
  stopwatch,
  ca_gm,
  ca_master,
  ca_elite,
  ca_hard,
  ca_med,
  ca_easy,
  achieve_quiver,
  achieve_cape,
  mega_bow,
  mega_staff,
  mega_scythe,
  type_unknown,
  type_main,
  type_iron,
  type_hcim,
  type_uim,
  type_gim,
  type_hcgim,
  type_ugim,
  type_snowflake,
  defaultImage,
} from "./imageImports";

export const accountTypes = new Map<string, any>([
  ["MAIN", type_main],
  ["IRON", type_iron],
  ["HCIM", type_hcim],
  ["UIM", type_uim],
  ["GIM", type_gim],
  ["HCGIM", type_hcgim],
  ["UGIM", type_ugim],
  ["SNOWFLAKE", type_snowflake],
]);

export const caIcons = new Map<number, any>([
  [2525, ca_gm],
  [1841, ca_master],
  [1026, ca_elite],
  [394, ca_hard],
  [148, ca_med],
]);

export const achievementIcons = [
  { prop: "has_quiver", img: achieve_quiver },
  { prop: "has_infernal", img: achieve_cape },
  { prop: "has_scythe", img: mega_scythe },
  { prop: "has_shadow", img: mega_staff },
  { prop: "has_tbow", img: mega_bow },
];
